### PR TITLE
Iteration4 bookmarks page

### PR DESCRIPTION
**Pull request by ThanadolU**
I added a button for adding and removing a restaurant to "My Bookmarks".

image

Then, I created a page to show "My Bookmarks" of the users.

image

### CODE REVIEW

**Comment by thanidacwn** [comment]
I think, it should use bookmark icon instead button.

**Review by thanidacwn — CHANGES_REQUESTED** [review]
Following last comment.

**Review by ThanadolU — COMMENTED** [review]
I've changed it

**Review by PanupunJanin — COMMENTED** [review]
Please resolve the conflict and as I see, the function works wonder.

**Review by thanidacwn — APPROVED** [review]
I already resolved conflict for you, and bookmarks look nice now. can merge it!

**Review by thanidacwn — CHANGES_REQUESTED** [review]
pls change test for pass before merge. And then can merge it

**Pull request merged**
